# rifa-online-frontend/nginx.conf

server {
  listen 80;
  server_name localhost;

  # Define a raiz onde nossos arquivos React estão
  root /usr/share/nginx/html;

  # Tenta servir o arquivo pedido. Se não achar,
  # serve o index.html. Isso é CRUCIAL para o React Router funcionar.
  location / {
    try_files $uri $uri/ /index.html;
  }
}