version: "3.7"

services:
  # --- 1. Serviço da Base de Dados (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: rifa-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Salva os dados localmente
    restart: unless-stopped
    networks:
      - rifa-net # Conecta-se apenas à rede interna do app

  # --- 2. Serviço do Backend (Go) ---
  backend:
    # Use a imagem que você subiu para o Docker Hub
    image: emaildoissa/rifa-online:backend
    container_name: rifa-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # O backend fala com o DB pelo nome do serviço 'db'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      GIN_MODE: release # Modo de produção para o Go/Gin
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}
      # As ENVs do ASAAS não são mais necessárias
    networks:
      - rifa-net      # Rede interna para falar com o 'db'
      - rede_interna  # Rede do Traefik para ser acessado
    labels:
      - "traefik.enable=true"
      # --- Defina o subdomínio da sua API ---
      - "traefik.http.routers.rifa-api.rule=Host(`api.rifa.automacao.free.nf`)"
      - "traefik.http.routers.rifa-api.entrypoints=websecure"
      - "traefik.http.routers.rifa-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.rifa-api.loadbalancer.server.port=8080" # Porta interna do Go
      - "traefik.docker.network=rede_interna" # Diz ao Traefik para usar esta rede

  # --- 3. Serviço do Frontend (React + Nginx) ---
  frontend:
    # Use a imagem que você subiu para o Docker Hub
    image: emaildoissa/rifa-online:frontend
    container_name: rifa-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - rifa-net      # Rede interna para falar com o 'backend' (embora o Nginx não precise)
      - rede_interna  # Rede do Traefik para ser acessado
    labels:
      - "traefik.enable=true"
      # --- Defina o subdomínio principal da sua Rifa ---
      - "traefik.http.routers.rifa-frontend.rule=Host(`rifa.automacao.free.nf`)"
      - "traefik.http.routers.rifa-frontend.entrypoints=websecure"
      - "traefik.http.routers.rifa-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.rifa-frontend.loadbalancer.server.port=80" # Porta interna do Nginx
      - "traefik.docker.network=rede_interna" # Diz ao Traefik para usar esta rede

volumes:
  pgdata: # Volume para persistir os dados do banco

networks:
  rifa-net: # Nova rede interna SÓ para este app
    name: rifa-net
    driver: bridge
  rede_interna: # Sua rede existente do Traefik e n8n
    external: true