# (Linha "version: '3.8'" REMOVIDA, pois é obsoleta)

services:
  # --- 1. Serviço da Base de Dados (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: rifa-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # --- 2. Serviço do Backend (Go) ---
  backend:
    build: ./rifa-online-backend
    # --- CORREÇÃO AQUI ---
    # Adicione esta linha para nomear a imagem para o Docker Hub
    image: emaildoissa/rifa-online:backend
    # --- FIM DA CORREÇÃO ---
    container_name: rifa-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_WEBHOOK_TOKEN: ${ASAAS_WEBHOOK_TOKEN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}

  # --- 3. Serviço do Frontend (React + Nginx) ---
  frontend:
    build: ./rifa-online-frontend
    # --- CORREÇÃO AQUI ---
    # Adicione esta linha para nomear a imagem para o Docker Hub
    image: emaildoissa/rifa-online:frontend
    # --- FIM DA CORREÇÃO ---
    container_name: rifa-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata: